# Generated by Django 4.1.7 on 2023-03-01 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_policy_plates'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='plates',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.plate'),
        ),
    ]
