# Generated by Django 4.1.7 on 2023-03-01 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_policy_plates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='plates',
        ),
        migrations.AlterField(
            model_name='record',
            name='execution_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 22, 15, 30, 255228)),
        ),
        migrations.AddField(
            model_name='policy',
            name='plates',
            field=models.ManyToManyField(to='app.plate'),
        ),
    ]
