# Generated by Django 4.1.7 on 2023-03-01 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_policy_plates_alter_record_execution_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='password',
            field=models.CharField(default='!QAZxsw2', max_length=45),
        ),
        migrations.AddField(
            model_name='plate',
            name='user',
            field=models.CharField(default='root', max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='execution_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 22, 45, 59, 555959)),
        ),
    ]
