# Generated by Django 4.1.7 on 2023-03-01 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_plate_password_plate_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='policy_path',
        ),
        migrations.AddField(
            model_name='policy',
            name='inventory',
            field=models.FilePathField(default=None),
        ),
        migrations.AddField(
            model_name='policy',
            name='playbook_path',
            field=models.FilePathField(default=None),
        ),
        migrations.AlterField(
            model_name='record',
            name='execution_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 22, 56, 11, 587909)),
        ),
    ]
